class HuumStatus:
    temperature: float
    door_closed: bool

class Huum:
    def __init__(self, username: str | None, password: str | None) -> None: ...
    async def open_session(self) -> None: ...
    async def close_session(self) -> None: ...
    async def status(self) -> HuumStatus: ...
